language: minimal

addons:
    apt:
        packages:
        - luarocks

install: luarocks install --local luacheck

script:
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 9.0.1 -m .pkgmeta.yml
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.5 -m .pkgmeta-classic.yml

notifications:
    email:
        on_success: never
        on_failure: always
